---
Name: shortcodable-codes
---

Shortcodable:
  shortcodable_classes:
    - FacebookShortcode
    - FullWidthImageShortcode
    - IframeShortcode
    - InstagramShortcode
    - TwitterShortcode
    - VimeoShortcode
    - YoutubeShortcode
